name: Update Worker.js

on:
  schedule:
    - cron: '0 0 * * 0' # 每周日 UTC 时间 0 点触发
  workflow_dispatch: # 添加手动触发功能

jobs:
  update-worker:
    runs-on: ubuntu-latest

    steps:
    # 检出仓库代码
    - name: Checkout repository
      uses: actions/checkout@v3

    # 拉取目标文件
    - name: Fetch latest worker.js
      run: |
        curl -o _worker.js https://raw.githubusercontent.com/yonggekkk/Cloudflare_vless_trojan/main/Vless_workers_pages/_worker.js

    # 提交更新
    - name: Commit and push changes
      run: |
        # 检查是否有变化
        if ! git diff --exit-code --quiet; then
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add _worker.js
          git commit -m "Update _worker.js (auto)"
          git push
        else
          echo "No changes detected, skipping commit."
