name: Update Worker.js

on:
  schedule:
    - cron: '0 0 * * 0' # 每周日 UTC 时间 0 点触发
  workflow_dispatch: # 手动触发

jobs:
  update-worker:
    runs-on: ubuntu-latest

    steps:
    # 检出代码
    - name: Checkout repository
      uses: actions/checkout@v4

    # 拉取目标文件
    - name: Fetch latest worker.js
      run: |
        curl -o _worker.js https://raw.githubusercontent.com/yonggekkk/Cloudflare_vless_trojan/main/Vless_workers_pages/_worker.js

    # 部署到 Cloudflare Workers
    - name: Deploy to Cloudflare
      run: npx wrangler deploy _worker.js

    # 删除历史记录
    - name: Cleanup previous workflow runs
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        gh auth login --with-token <<< "${GH_TOKEN}"
        # 获取当前工作流的 ID
        WORKFLOW_ID=$(gh workflow list --json id,name | jq -r '.[] | select(.name == "Update Worker.js") | .id')
        # 删除所有之前的运行记录，保留当前运行
        gh run list --workflow "$WORKFLOW_ID" --json databaseId,status | \
        jq -r '.[] | select(.status == "completed") | .databaseId' | \
        xargs -I {} gh run delete {} --confirm
